#spring.application.name=user-service
#server.port=8889
##DB
#spring.datasource.url=jdbc:mysql://localhost:3306/user_db?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=huyhuyhuy1312
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
##kafka
#spring.kafka.bootstrap-servers=localhost:29092
#kafka.topic.user-events=create_user
#kafka.consumer.group-id=user-service-group
##devtools
#spring.devtools.restart.enabled=false
#spring.devtools.livereload.enabled=false

spring:
  application:
    name: user-service
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:8888